# Nom de la pipeline
name: Task CI/CD Pipeline

# Ecouter des evenements
on:
  # Quand on fait pour un  push dans toutes les branches
  push:
    branches:
      - "*"
  # Quand on fait un pull_request
  pull_request:
    branches:
      - "*"

# Les activites a faire dans la piplene
jobs:
  # 1er job verifier le sytaxe du code
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check lint code with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=85
